# Generated by Django 4.2.23 on 2025-07-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cartbill_cart_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_default',
            new_name='is_selected',
        ),
    ]
