# Generated by Django 4.2.23 on 2025-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_is_default_address_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appartment',
            field=models.TextField(),
        ),
    ]
