# Generated by Django 4.2.23 on 2025-07-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0004_fooditem_is_veg'),
        ('customer', '0005_alter_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='restaurent.fooditem'),
        ),
    ]
