# Generated by Django 4.2.23 on 2025-07-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_pecentage', models.BooleanField(default=False)),
            ],
        ),
    ]
