# Generated by Django 4.2.23 on 2025-07-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_offers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ['-id'], 'verbose_name': 'offers', 'verbose_name_plural': 'offerss'},
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='Offer',
            new_name='offer',
        ),
        migrations.AlterModelTable(
            name='offers',
            table='offers',
        ),
    ]
