# Generated by Django 4.2.23 on 2025-07-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0004_fooditem_is_veg'),
        ('customer', '0009_alter_offers_options_rename_offer_offers_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('delivery_charge', models.IntegerField(default=0)),
                ('order_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'PALCEORDER'), ('6', 'ACCEPT'), ('2', 'SHIPPED'), ('3', 'ONTHEWAY'), ('4', 'DELIVERD'), ('5', 'CANCELED')], max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'orders',
                'verbose_name_plural': 'orderess',
                'db_table': 'order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'order_item',
                'ordering': ['-id'],
            },
        ),
    ]
