# Generated by Django 4.2.23 on 2025-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PALCEORDER', 'PL'), ('ACCEPT', 'AC'), ('SHIPPED', 'SH'), ('ONTHEWAY', 'DI'), ('DELIVERD', 'DL'), ('CANCELED', 'CL')], max_length=255),
        ),
    ]
