# Generated by Django 4.2.23 on 2025-07-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'food category',
                'verbose_name_plural': 'food categories',
                'db_table': 'food_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='fooditem')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.foodcategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'fooditem',
                'verbose_name_plural': 'fooditems',
                'db_table': 'food_item',
                'ordering': ['-id'],
            },
        ),
    ]
