# Generated by Django 4.2.23 on 2025-07-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0002_foodcategory_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditem', to='restaurent.foodcategory'),
        ),
    ]
