# Generated by Django 4.2.23 on 2025-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0003_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
