# Generated by Django 4.2.23 on 2025-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0004_fooditem_is_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to='slider'),
        ),
    ]
