# Generated by Django 4.2.23 on 2025-07-18 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mamager',
            new_name='Manager',
        ),
    ]
